[versions]
androidx-core = "1.17.0"
androidx-activity = "1.13.0"
androidx-navigation = "2.9.8"
androidx-webkit = "1.16.0"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"
junit4 = "4.13.2"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidx-webkit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
